In [1]:
import pandas as pd

In [2]:
data = {'Category': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C']}

In [3]:
df = pd.DataFrame(data)
df.head()

  Category
0        A
1        B
2        C
3        A
4        B

In [4]:
one_hot_encoded_df = pd.get_dummies(df, columns=['Category'])
one_hot_encoded_df

   Category_A  Category_B  Category_C
0        True       False       False
1       False        True       False
2       False       False        True
3        True       False       False
4       False        True       False
5       False       False        True
6        True       False       False
7       False        True       False
8       False       False        True

In [14]:
one_hot_encoded_df = pd.get_dummies(df, columns=['Category'], prefix='Dummy')
one_hot_encoded_df

   Dummy_A  Dummy_B  Dummy_C
0     True    False    False
1    False     True    False
2    False    False     True
3     True    False    False
4    False     True    False
5    False    False     True
6     True    False    False
7    False     True    False
8    False    False     True

In [6]:
one_hot_encoded_df = pd.get_dummies(df, columns=['Category'], prefix='Dummy',drop_first=True )
one_hot_encoded_df

   Dummy_B  Dummy_C
0    False    False
1     True    False
2    False     True
3    False    False
4     True    False
5    False     True
6    False    False
7     True    False
8    False     True

In [7]:
df.head()

  Category
0        A
1        B
2        C
3        A
4        B